# Generated by Django 3.2.4 on 2021-06-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('data_source_type', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_id', models.CharField(max_length=1000)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('time_date', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('acreage', models.CharField(blank=True, max_length=200, null=True)),
                ('percent', models.CharField(blank=True, max_length=200, null=True)),
                ('cause', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('primary', models.CharField(blank=True, max_length=200, null=True)),
                ('perimeter', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
