# Generated by Django 3.2.6 on 2022-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('data_source_type', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_id', models.CharField(max_length=1000)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('time_date', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('acreage', models.CharField(blank=True, max_length=200, null=True)),
                ('percent', models.CharField(blank=True, max_length=200, null=True)),
                ('cause', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('primary', models.CharField(blank=True, max_length=200, null=True)),
                ('perimeter', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='red_flag_data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('polygon', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_time', models.CharField(max_length=2000)),
            ],
        ),
    ]
